channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - r-base=4.3.2
  - r-lintr=3.1.1
  - r-ggplot2=3.5.1
  - r-tidyverse=2.0.0
  - r-cowplot=1.1.3
  - r-reshape2=1.4.4
  - r-glmnet=4.1.8
  - r-pbapply=1.7.2
  - r-dplyr=1.1.4
  - r-devtools=2.4.5
  - matplotlib=3.8.4
  - numpy=1.26.4
  - natsort=8.4.0
  - tqdm=4.66.2
  - pandas=2.2.2
