channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - r-base=4.3.2
  - r-lintr=3.1.1
  - r-ggplot2=3.5.1
  - r-tidyverse=2.0.0
  - r-cowplot=1.1.3
  - r-reshape2=1.4.4
  - r-glmnet=4.1.8
  - r-pbapply=1.7.2
  - r-dplyr=1.1.4
  - matplotlib
  - numpy
  - natsort
  - tqdm
  - pandas
